cmake_minimum_required(VERSION 3.22...3.29)
project(SeatCanvasKit LANGUAGES C CXX)


list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake/modules")

include(Utils)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release)
endif()


set(PROJECT_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR})
set(PROJECT_ROOT_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/include)
set(PROJECT_THIRD_PARTY_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR}/third_party)

# set(_SEATCANVAS_PREV_BUILD_TYPE "${CMAKE_BUILD_TYPE}")
# set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)

set(TGFX_BUILD_SVG ON CACHE INTERNAL "")
set(TGFX_BUILD_LAYERS ON CACHE INTERNAL "")

if(MACOS OR IOS)
    set(TGFX_USE_METAL ON CACHE INTERNAL "")
endif()

add_subdirectory(third_party/tgfx)


set(JSON_BuildTests OFF CACHE INTERNAL "")
set(JSON_Install OFF CACHE INTERNAL "")
add_subdirectory(third_party/tgfx/third_party/json)

# set(CMAKE_BUILD_TYPE "${_SEATCANVAS_PREV_BUILD_TYPE}" CACHE STRING "" FORCE)

add_subdirectory(src/SeatCanvas)
