#!/bin/bash

export PATH=${HOME}/.local/bin:/opt/homebrew/bin:$PATH

CPP_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(h|hpp|c|cpp|mm)$')
SWIFT_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep '\.swift$')

if [ -z "$CPP_FILES" ] && [ -z "$SWIFT_FILES" ]; then
  exit 0
fi

if [ -n "$CPP_FILES" ]; then
  clang-format -i $CPP_FILES
  git add $CPP_FILES
fi

if [ -n "$SWIFT_FILES" ]; then
  swiftformat $SWIFT_FILES
  git add $SWIFT_FILES
fi

exit 0