name: autotest

on:
  workflow_dispatch:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]

jobs:
  ci-runners:
    uses: ./.github/workflows/ci-runners.yml

  third-party:
    needs: ci-runners
    uses: ./.github/workflows/third-party.yml
    with:
      runner: ${{ needs.ci-runners.outputs.linux }}

  autotest:
    needs: [ci-runners, third-party]
    runs-on: ${{ needs.ci-runners.outputs.macos }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Get Third-Party Cache
        uses: actions/cache/restore@v4
        with:
          path: third_party
          key: third-party-${{ hashFiles('DEPS') }}
          restore-keys: third-party-

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: cmake ninja yasm git-lfs

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.4.1"

      - name: Run autotest
        run: ./autotest.sh clean

      - name: Upload Test Output
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: autotest_out
          path: tests/out/
          if-no-files-found: ignore
